# Generated by Django 5.2.1 on 2025-05-15 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studentgroup_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='teachers',
            field=models.ManyToManyField(related_name='st_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
